(() => {
  'use strict';

  window.ACOLYTE_REAL_CASES = {
    industries: [
      { key: 'agriculture', label: 'Agriculture' },
      { key: 'industry', label: 'Industrie' },
      { key: 'services', label: 'Services' },
      { key: 'finance', label: 'Finance' },
      { key: 'insurance', label: 'Assurance' },
      { key: 'automotive', label: 'Automobile' },
      { key: 'retail', label: 'Retail' },
      { key: 'software', label: 'Logiciel' }
    ],
    levels: [
      { key: 'individual', label: 'Individu' },
      { key: 'knowledge', label: 'Connaissance' },
      { key: 'process', label: 'Processus' },
      { key: 'agent', label: 'Agent' },
      { key: 'tool', label: 'Outil métier' }
    ],
    cases: [
      {
        id: 'sharp-seed-memory',
        company: 'Sharp & Sharp Certified Seed',
        country: 'USA',
        industry: 'agriculture',
        industryLabel: 'Agriculture',
        size: 'PME familiale',
        levels: ['knowledge'],
        levelLabel: 'Connaissance',
        problem: 'Des décennies de registres agricoles existaient déjà, mais restaient difficiles à retrouver au moment où le travail se faisait.',
        solution: 'Les registres manuscrits ont été numérisés et rendus interrogeables avec ChatGPT pour retrouver rapidement les pratiques, dates et rendements passés.',
        architecture: ['REGISTRES', 'NUMÉRISATION', 'CONNAISSANCE', 'RECHERCHE IA', 'RÉPONSE TERRAIN'],
        results: ['Historique agricole rendu accessible au quotidien.', 'Les décisions terrain peuvent s’appuyer sur une expérience déjà accumulée.'],
        takeaway: 'L’entreprise savait déjà beaucoup de choses. Le problème était l’accès à cette connaissance.',
        source: { publisher: 'OpenAI', url: 'https://openai.com/index/small-business-stories/', date: '2026-02-04', evidenceType: 'reported', evidenceStrength: 'medium' },
        caveat: 'Résultat décrit par OpenAI et la famille Sharp ; aucun déploiement technique détaillé n’est publié.'
      },
      {
        id: 'original-tamale-tool',
        company: 'The Original Tamale Co.',
        country: 'USA',
        industry: 'retail',
        industryLabels: ['retail'],
        industryLabel: 'Retail / Food',
        size: 'PME familiale',
        levels: ['individual', 'tool'],
        levelLabel: 'Individu → Outil',
        problem: 'Les clients avaient du mal à savoir sur quels marchés retrouver la marque, et l’entreprise voulait un outil de recherche sans attendre un projet logiciel complet.',
        solution: 'Un utilisateur non développeur a utilisé ChatGPT pour construire et publier un farmers market tracker utilisable sur le site.',
        architecture: ['PERSONNE', 'CONVERSATION IA', 'CODE', 'OUTIL UTILISABLE'],
        results: ['Un tracker de marchés construit et lancé le même après-midi.', 'Une idée métier devient un petit outil accessible aux clients.'],
        takeaway: 'L’IA ne sert pas seulement à écrire : elle peut aider quelqu’un à créer un outil métier ciblé.',
        source: { publisher: 'OpenAI', url: 'https://openai.com/index/small-business-stories/', date: '2026-02-04', evidenceType: 'reported', evidenceStrength: 'medium' },
        caveat: 'Cas rapporté par OpenAI ; le code et les métriques d’usage ne sont pas publiés.'
      },
      {
        id: 'ris-support-memory',
        company: 'RIS d.o.o.',
        country: 'Croatie',
        industry: 'software',
        industryLabels: ['software', 'services'],
        industryLabel: 'Logiciel / Services',
        size: 'PME',
        levels: ['knowledge', 'process'],
        levelLabel: 'Connaissance + Processus',
        problem: 'Les demandes de support arrivaient par email et téléphone, avec une forte charge de classification, de triage et de réponse répétitive.',
        solution: 'Un assistant alimenté par les FAQ, manuels et historiques utilise recherche, RAG et classification pour proposer une réponse au support.',
        architecture: ['FAQ + MANUELS + HISTORIQUE', 'RAG / SEARCH', 'CLASSIFICATION', 'RÉPONSE PROPOSÉE', 'SUPPORT'],
        results: ['Les demandes peuvent être traitées avec une disponibilité élargie.', 'Les équipes peuvent réserver davantage de temps aux demandes complexes.'],
        takeaway: 'La mémoire utile n’est pas un souvenir vague : c’est une connaissance retrouvable, reliée à un processus et à une validation.',
        source: { publisher: 'EDIH Adriatic Croatia / Commission européenne', url: 'https://european-digital-innovation-hubs.ec.europa.eu/knowledge-hub/success-stories/ai-powered-digital-assistant-customer-support', date: '2025-07-10', evidenceType: 'reported', evidenceStrength: 'medium' },
        caveat: 'Le projet est présenté comme un pilote ; les gains de long terme sont décrits comme des perspectives.'
      },
      {
        id: 'plus-simple-document',
        company: '+Simple',
        country: 'France',
        industry: 'insurance',
        industryLabel: 'Assurance',
        size: 'Scale-up',
        levels: ['process'],
        levelLabel: 'Processus',
        problem: 'Le traitement documentaire et la validation des dossiers ralentissaient la relation avec les courtiers et les clients.',
        solution: 'Un assistant génératif s’appuie sur des données documentaires et du RAG pour extraire, pré-valider et laisser les exceptions aux équipes.',
        architecture: ['DOCUMENT', 'EXTRACTION', 'PRÉ-VALIDATION', 'EXCEPTIONS', 'HUMAIN'],
        results: ['Temps de traitement documentaire annoncé de 4 minutes à 60 secondes.', 'Pré-validation automatisée annoncée à 85 % et 87 heures gagnées par mois.'],
        takeaway: 'On n’automatise pas le jugement : on automatise les tâches répétitives et on laisse les exceptions aux humains.',
        source: { publisher: 'Devoteam', url: 'https://www.devoteam.com/fr/success-story/plus-simple-assistant-virtuel-ia-assurance/', date: 'Date non affichée', evidenceType: 'reported', evidenceStrength: 'medium' },
        caveat: 'Chiffres rapportés dans une étude de cas fournisseur ; ils ne sont pas présentés comme une mesure indépendante.'
      },
      {
        id: 'groupeactive-propale',
        company: 'GroupeActive',
        country: 'France',
        industry: 'services',
        industryLabel: 'Services B2B',
        size: 'PME',
        levels: ['agent'],
        levelLabel: 'Agent',
        problem: 'Les experts perdaient une journée à rédiger des propositions commerciales, alors que la préparation de l’offre n’était pas leur cœur de métier.',
        solution: 'GAIA Propale transforme les notes de rendez-vous en chapitres structurés de proposition commerciale, puis laisse l’expert relire et valider.',
        architecture: ['NOTES DE RENDEZ-VOUS', 'AGENT GAIA PROPale', 'STRUCTURATION', 'RELECTURE', 'PROPOSITION COMMERCIALE'],
        results: ['Temps de rédaction annoncé à deux heures au lieu d’une journée.', 'Temps de signature annoncé divisé par quatre.'],
        takeaway: 'Un agent peut prendre en charge plusieurs étapes d’un travail commercial, sans prendre la décision à la place de l’expert.',
        source: { publisher: 'Microsoft Customer Stories', url: 'https://www.microsoft.com/fr-fr/customers/story/24148-groupeactive-microsoft-teams', date: '2025-05-27', evidenceType: 'reported', evidenceStrength: 'medium' },
        caveat: 'Résultats rapportés par GroupeActive dans une étude de cas Microsoft ; la validation humaine reste dans le flux.'
      },
      {
        id: 'qonto-human-gate',
        company: 'Qonto',
        country: 'Europe',
        industry: 'finance',
        industryLabel: 'Finance',
        size: 'Entreprise en croissance',
        levels: ['agent'],
        levelLabel: 'Agent + Human Gate',
        problem: 'Les tâches administratives financières répétitives prennent du temps et touchent à des données et actions sensibles.',
        solution: 'Les agents préparent transferts, factures ou analyses, puis demandent une confirmation explicite avant toute action financière.',
        architecture: ['DEMANDE', 'PRÉPARATION', 'OUTILS', 'ACTION PROPOSÉE', 'HUMAN GATE', 'EXÉCUTION'],
        results: ['Aucun mouvement d’argent sans approbation explicite de l’utilisateur.', 'Les études de cas annoncent des transferts deux fois plus rapides et des factures créées trois fois plus vite.'],
        takeaway: 'Autonomie ne signifie pas absence de contrôle : l’agent prépare, l’humain décide.',
        source: { publisher: 'Claude by Anthropic / Qonto', url: 'https://claude.com/customers/qonto', date: '2026-09-03', evidenceType: 'reported', evidenceStrength: 'medium' },
        caveat: 'Étude de cas fournisseur ; les gains sont annoncés par Qonto et ses partenaires.'
      },
      {
        id: 'adria-communication',
        company: 'Adria P.A.',
        country: 'Croatie',
        industry: 'automotive',
        industryLabel: 'Automobile',
        size: 'PME',
        levels: ['knowledge'],
        levelLabel: 'Connaissance / RAG',
        problem: 'Un concessionnaire Renault et Dacia devait mieux gérer un volume important de demandes clients et d’activités de service.',
        solution: 'Un assistant de communication s’appuie sur la connaissance interne et les processus commerciaux pour aider les équipes à répondre plus vite et plus régulièrement.',
        architecture: ['DOCUMENTATION', 'PROCESSUS COMMERCIAUX', 'CONNAISSANCE INTERNE', 'ASSISTANT IA', 'RÉPONSE CLIENT'],
        results: ['Le cas décrit une amélioration attendue des interactions clients et des processus internes.', 'Aucun gain chiffré observé n’est affiché dans cette fiche.'],
        takeaway: 'Une base de connaissances peut soutenir la relation client sans devenir le moteur de raisonnement lui-même.',
        source: { publisher: 'EDIH Adriatic Croatia / Commission européenne', url: 'https://edihadria.eu/en/unaprjedenje-komunikacije-iskorak-s-ai-asistentom/', date: '2024-11-21', evidenceType: 'projected', evidenceStrength: 'low' },
        caveat: 'La source décrit l’objectif et la solution ; les résultats sont à considérer comme projetés tant qu’une mesure publiée n’existe pas.'
      }
    ]
  };
})();
